### ISSUE TITLE
Should work without DOM / window

### ISSUE THREAD

**Issue by austinhallock** [Zorium/zorium#45] opened 2015-03-02 05:17 UTC
ReferenceError: window is not defined
  at new Router (/home/austin/dev/clay-mobile/node_modules/zorium/dist/zorium.js:361:6)
  at Object.module.exports.__bind (/home/austin/dev/clay-mobile/node_modules/zorium/dist/zorium.js:491:19)

**Comment by Zolmeister** [comment] 2015-03-02 05:24
duplicate of #22

**Closed by Zolmeister** 2015-03-02 05:24 UTC

**Comment by austinhallock** [comment] 2015-03-02 05:25
Can we get a quicker fix for that? So we can include modules that require zorium (eg User model on clay-mobile) inside of server.coffee

**Comment by Zolmeister** [comment] 2015-03-02 05:43
Why do we need it inside of server.coffee?
Also, see if `observe = require 'zorium/observe'` works (though no guarantees on it being accepted)

**Comment by austinhallock** [comment] 2015-03-02 05:50
Game model* for the getIcon method

**Comment by Zolmeister** [comment] 2015-03-02 05:59
As commented in PR, add a TODO instead.
